#!/usr/bin/env bash

# Update files
sudo apt update && sudo apt upgrade -y

# Install basic packages
sudo apt install -y wget curl nano git unzip

# Loads .profile for bashrc too
echo "# Loads .profile
if [ -f $HOME/.profile ]; then
    . $HOME/.profile
fi" >>$HOME/.bashrc

# Dotfiles repository
if [ ! -d $HOME/.dotfiles ]; then
  git clone --depth=1 --bare https://github.com/nisee-org/dotfiles.git $HOME/.dotfiles
  # I know its hard but sometimes we just accept I cannot do it with functions or aliases
  /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME $@ config --local status.showUntrackedFiles no
  /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME $@ fetch
  /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME $@ checkout master --force
fi

# Sets up docker
if ! command -v docker &>/dev/null; then
  sudo apt install -y ca-certificates curl gnupg
  sudo install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  sudo chmod a+r /etc/apt/keyrings/docker.gpg
  echo \
    "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
    "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" |
    sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
  sudo apt update
  sudo apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  sudo usermod -aG docker $(whoami)
fi


# Sets up Node & NVM
if ! command -v node &>/dev/null; then
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
  . "$HOME/.nvm/nvm.sh"

  # Install and uses node 21
  nvm install v21
  nvm alias default v21
  npm i -g pnpm npm yarn
fi

# Sets up bun.js
if ! command -v bun &>/dev/null; then
  curl -fsSL https://bun.sh/install | bash

  # Resets .zshrc
  /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME $@ checkout .zshrc --force
fi